name: 05 - Event Filters with Activity Types

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  validate-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR validation message
        run: echo "Running whenever a PR is opened or synchronized AND base branch is main"