name: 09 - Using Functions

on:
    workflow_dispatch:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR title
              run: echo "${{github.event.pull_request.title}}"
            - name: Print PR labels
              run: |
                cat << EOF
                ${{toJSON( github.event.pull_request.labels) }}
                EOF
            - name: Bug step
              if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
              run: echo "I am a bugfix"
            - name: Sleep 20 seconds
              run: sleep 20
            - name: Failing step
              run: exit 1
            - name: I will be scippred
              if: ${{success()}}
              run: echo "I will print if previous steps seceed"
            - name: I will execute
              if: ${{failure()}}
              run: echo "I will print if any of previous steps failed"
            - name: I will execute
              if: ${{!cancelled()}}
              run: echo "W will aplways print, except when workflow is cancelled"
            - name: I will execute if cancelled
              if: ${{cancelled()}}
              run: echo "I will print if the workflow is cancelled"